@startuml

actor Owner
boundary routes
boundary view.roles.ejs
control rol.controller.js
entity rol.model.js
database leadtics

Owner -> routes : GET /roles/editarRol/:id
activate routes

routes -> rol.controller.js : getEditarRol
deactivate routes
activate rol.controller.js

rol.controller.js -> rol.model.js : fetchById()
deactivate rol.controller.js
activate rol.model.js

rol.model.js -> leadtics : db.execute("SELECT * FROM roles WHERE id = ? AND FechaHoraEliminado IS NULL")
deactivate rol.model.js
activate leadtics

leadtics --> rol.model.js : rol
deactivate leadtics
activate rol.model.js

rol.model.js --> rol.controller.js :rol
deactivate rol.model.js
activate rol.controller.js

rol.controller.js -> view.roles.ejs : response.render('roles/editarRol', {IDRol})
deactivate rol.controller.js

view.roles.ejs -> Owner : HTML
deactivate view.roles.ejs

Owner -> routes : POST /roles/editarRol/:id
activate routes

routes -> rol.controller.js : postEditarRol
deactivate routes

rol.controller.js -> rol.model.js : updateRolById()
activate rol.model.js

rol.model.js -> leadtics : db.execute("UPDATE roles SET nombre = ?, DescripcionRol = ? WHERE id = ?")
deactivate rol.model.js

leadtics --> rol.model.js : result
activate rol.model.js

rol.model.js --> rol.controller.js : result
deactivate rol.model.js

rol.controller.js -> routes : redirect /roles
deactivate rol.controller.js

routes -> Owner : HTML
deactivate routes

@enduml